name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t flask-app .

  test:
    name: Run Container & Health Check
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image (again for isolation)
        run: |
          docker build -t flask-app .

      - name: Run Docker Container
        run: |
          docker run -d -p 5000:5000 --name flask-test flask-app
          sleep 5  # Wait for the app to start

      - name: Test Health Check
        run: |
          curl --fail http://localhost:5000 || (echo "Health check failed" && exit 1)

  deploy:
    name: Deploy (Simulated)
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image (again for simulation)
        run: |
          docker build -t flask-app .

      - name: Run Docker Container (Deploy Simulation)
        run: |
          docker run -d -p 80:5000 --name flask-deploy flask-app
          echo "✅ Flask App Deployed on localhost (simulated)"
